### ISSUE TITLE
Update ir prox examples

### ISSUE THREAD

**Issue by shamlian** [iRobotEducation/irobot-edu-python-sdk#22]
Update IR prox examples to use get_packed_ir_proximity() and add a comment that this will only work with firmware G.3.0 and greater.

**Comment by shamlian** [comment]
Even better -- create a new get_ir_prox() command that intelligently returns either the 7- or 6-sensor response.

**Comment by shamlian** [comment]
Committed to pre_0.4.0

**Comment by felipenmartins** [comment]
A few hours ago the function get_ir_proximity() started to work fine in the Python Web Playground (returning all 7 sensor values).
Thanks for the update!
