### ISSUE TITLE
`get_touch_sensors` should only return two values for Create 3

### ISSUE THREAD

**Issue by shamlian** [iRobotEducation/irobot-edu-python-sdk#36]
`get_touch_sensors` is defined in the `Robot` class to return four sensors, which doesn't make sense for Create 3. Someone should fix that.

_See original post by @shamlian in https://github.com/iRobotEducation/irobot-edu-python-sdk/issues/35#issuecomment-1889886568_

**Comment by scottcandy34** [comment]
**NOTE:** you can shorten the touch handler `any` operation. The `not event.condition` can pulled out as such...

`not event.condition and (self.touch_sensors.front_left or self.touch_sensors.front_right or self.touch_sensors.back_left or self.touch_sensors.back_right)`

This will fail off the start for event.condition, not having extra checks will increase speed.

**Comment by shamlian** [comment]
Good point. Would you agree that the two other checks on the value of `any` in the `elif` statements just below are redundant?

**Comment by scottcandy34** [comment]
yes I was just looking at that too. agreed

**Comment by shamlian** [comment]
All right, I'll be pushing a fix to the branch for this soon.
