### ISSUE TITLE
Create 3 SDK: ValueError: badly formed hexadecimal UUID string

### ISSUE THREAD

**Issue by Kahan64bit** [iRobotEducation/irobot-edu-python-sdk#46]
I am trying to connect to an irobot; however, there are many in the vicinity. How can I get the specific BLE ID for the robot?
Create3(Bluetooth(**What goes here**))

**Comment by shamlian** [comment]
If you know the robot's name (which can be set using the web server, though this requires an application restart after saving), you can use Create3(Bluetooth('robot-name')). When you connect to the robot in this manner, I believe it prints the address to the screen upon connection. You could then subsequently connect to the robot with something like `Create3(Bluetooth(address='hex-address'))`, if memory serves.

**Comment by Kahan64bit** [comment]
Thank you this works well.
